---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lakwpxhf/zabana.store
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/rsync -av --delete --exclude='.git' --exclude='.env' --exclude='storage/*' --exclude='bootstrap/cache/*' --exclude='node_modules' ./ $DEPLOYPATH/
