---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lakwpxhf/zabana.store
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/rsync -av --exclude='.git' --exclude='.env' --exclude='node_modules' --exclude='storage/*' --exclude='bootstrap/cache/*' ./ $DEPLOYPATH/
