<?php

use App\Services\Shipping\Drivers\GuepexDriver;
use App\Services\Shipping\Drivers\MaystroDriver;
use App\Services\Shipping\Drivers\NoestDriver;
use App\Services\Shipping\Drivers\ProcolisDriver;
use App\Services\Shipping\Drivers\YalidineDriver;
use App\Services\Shipping\Drivers\ZrExpressDriver;

return [
    'request_timeout' => 15,
    'connect_timeout' => 5,
    'supported_order_status_map' => [
        'delivered' => 'delivered',
        'out_for_delivery' => 'out_for_delivery',
        'returned' => 'returned',
        'failed' => 'failed',
        'canceled' => 'canceled',
    ],
    'carriers' => [
        'noest' => [
            'key' => 'noest',
            'display_name' => 'NOEST',
            'website' => 'https://app.noest-dz.com',
            'driver' => NoestDriver::class,
            'status' => true,
            'supported' => true,
            'integration_status' => 'supported',
            'supports_home_delivery' => true,
            'supports_desk_delivery' => true,
            'supports_rate_lookup' => true,
            'supports_tracking' => false,
            'supports_label' => false,
            'supports_create_shipment' => true,
            'credential_fields' => [
                ['key' => 'noest_guid', 'label' => 'NOEST GUID', 'type' => 'text'],
                ['key' => 'api_token', 'label' => 'API Token', 'type' => 'password'],
            ],
            'required_fields' => ['noest_guid', 'api_token'],
        ],
        'yalidine' => [
            'key' => 'yalidine',
            'display_name' => 'Yalidine',
            'website' => 'https://yalidine.app',
            'driver' => YalidineDriver::class,
            'status' => true,
            'supported' => true,
            'integration_status' => 'supported',
            'base_url' => 'https://api.yalidine.app/v1',
            'supports_home_delivery' => true,
            'supports_desk_delivery' => true,
            'supports_rate_lookup' => true,
            'supports_tracking' => true,
            'supports_label' => true,
            'supports_create_shipment' => true,
            'credential_fields' => [
                ['key' => 'api_id', 'label' => 'api_id', 'type' => 'text'],
                ['key' => 'api_token', 'label' => 'api_token', 'type' => 'password'],
                ['key' => 'from_wilaya_id', 'label' => 'from_wilaya_id', 'type' => 'text'],
            ],
            'required_fields' => ['api_id', 'api_token', 'from_wilaya_id'],
        ],
        'guepex' => [
            'key' => 'guepex',
            'display_name' => 'Guepex',
            'website' => 'https://guepex.app',
            'driver' => GuepexDriver::class,
            'status' => true,
            'supported' => true,
            'integration_status' => 'supported',
            'base_url' => 'https://api.guepex.app/v1',
            'supports_home_delivery' => true,
            'supports_desk_delivery' => true,
            'supports_rate_lookup' => true,
            'supports_tracking' => true,
            'supports_label' => true,
            'supports_create_shipment' => true,
            'credential_fields' => [
                ['key' => 'api_id', 'label' => 'api_id', 'type' => 'text'],
                ['key' => 'api_token', 'label' => 'api_token', 'type' => 'password'],
                ['key' => 'from_wilaya_id', 'label' => 'from_wilaya_id', 'type' => 'text'],
            ],
            'required_fields' => ['api_id', 'api_token', 'from_wilaya_id'],
        ],
        'zr_express' => [
            'key' => 'zr_express',
            'display_name' => 'ZR Express',
            'website' => 'https://zrexpress.com',
            'driver' => ZrExpressDriver::class,
            'status' => true,
            'supported' => true,
            'integration_status' => 'supported',
            'base_url' => 'https://procolis.com/api_v1',
            'supports_home_delivery' => true,
            'supports_desk_delivery' => true,
            'supports_rate_lookup' => true,
            'supports_tracking' => true,
            'supports_label' => false,
            'supports_create_shipment' => true,
            'credential_fields' => [
                ['key' => 'token', 'label' => 'api_token', 'type' => 'password'],
                ['key' => 'key', 'label' => 'api_secret', 'type' => 'password'],
            ],
            'required_fields' => ['token', 'key'],
        ],
        'maystro' => [
            'key' => 'maystro',
            'display_name' => 'Maystro Delivery',
            'website' => 'https://orders-management.maystro-delivery.com',
            'driver' => MaystroDriver::class,
            'status' => true,
            'supported' => true,
            'integration_status' => 'supported',
            'base_url' => 'https://orders-management.maystro-delivery.com',
            'supports_home_delivery' => true,
            'supports_desk_delivery' => true,
            'supports_pickup_point' => true,
            'supports_rate_lookup' => true,
            'supports_tracking' => true,
            'supports_label' => true,
            'supports_webhooks' => true,
            'supports_create_shipment' => true,
            'credential_fields' => [
                ['key' => 'store_token', 'label' => 'maystro_store_token', 'type' => 'password', 'required' => true],
                ['key' => 'store_id', 'label' => 'maystro_store_id', 'type' => 'text', 'required' => false],
            ],
            'required_fields' => ['store_token'],
        ],
        'procolis' => [
            'key' => 'procolis',
            'display_name' => 'Procolis',
            'website' => 'https://procolis.com',
            'driver' => ProcolisDriver::class,
            'status' => true,
            'supported' => true,
            'integration_status' => 'supported',
            'base_url' => 'https://procolis.com/api_v1',
            'supports_home_delivery' => true,
            'supports_desk_delivery' => true,
            'supports_rate_lookup' => true,
            'supports_tracking' => true,
            'supports_label' => false,
            'supports_create_shipment' => true,
            'credential_fields' => [
                ['key' => 'token', 'label' => 'api_token', 'type' => 'password'],
                ['key' => 'key', 'label' => 'api_secret', 'type' => 'password'],
            ],
            'required_fields' => ['token', 'key'],
        ],
    ],
];
